apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: ball
    version: base
    vm: temurin-17
  name: ball-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ball
      version: base
      vm: temurin-17
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        io.cilium.proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/8080/TCP/HTTP>"
        prometheus.io/scrape: "true"
      labels:
        project: mesh-arena
        app: ball
        version: base
        vm: temurin-17
    spec:
      containers:
      - image: quay.io/jotak/mesharena-ball:1.4.0
        imagePullPolicy: IfNotPresent
        name: ball-base
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: PCT_ERRORS
          value: "0"
        - name: RESISTANCE
          value: "80"
        - name: METRICS_ENABLED
          value: "1"
        - name: TRACING_ENABLED
          value: "1"
        - name: KAFKA_ADDRESS
          value: ""
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadiumsvc
        - name: JAEGER_SERVICE_NAME
          value: ball.default
        - name: JAEGER_SAMPLER_TYPE
          value: ratelimiting
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system:14268/api/traces
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: ball
  labels:
    project: mesh-arena
    app: ball
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: ball
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: stadium
    version: base
    vm: temurin-17
  name: stadium-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stadium
      version: base
      vm: temurin-17
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        io.cilium.proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/8080/TCP/HTTP>"
        prometheus.io/scrape: "true"
      labels:
        project: mesh-arena
        app: stadium
        version: base
        vm: temurin-17
    spec:
      containers:
      - image: quay.io/jotak/mesharena-stadium:1.4.0
        imagePullPolicy: IfNotPresent
        name: stadium-base
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "1"
        - name: TRACING_ENABLED
          value: "1"
        - name: KAFKA_ADDRESS
          value: ""
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: STADIUM_LOCALS
          value: Locals
        - name: STADIUM_VISITORS
          value: Visitors
        - name: STADIUM_NAME
          value: Commanderie
        - name: STADIUM_TOP
          value: "50"
        - name: STADIUM_LEFT
          value: "20"
        - name: STADIUM_SCALE
          value: "1.0"
        - name: STADIUM_MATCH_TIME
          value: "120"
        - name: JAEGER_SERVICE_NAME
          value: stadium.default
        - name: JAEGER_SAMPLER_TYPE
          value: ratelimiting
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system:14268/api/traces
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: stadiumsvc
  labels:
    project: mesh-arena
    app: stadium
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: stadium
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: ui
    version: base
    vm: temurin-17
  name: ui-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      version: base
      vm: temurin-17
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        sidecar.istio.io/statsInclusionPrefixes: cluster_manager,listener_manager,broker
        io.cilium.proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/8080/TCP/HTTP>"
        prometheus.io/scrape: "true"
      labels:
        project: mesh-arena
        app: ui
        version: base
        vm: temurin-17
    spec:
      containers:
      - image: quay.io/jotak/mesharena-ui:1.4.0
        imagePullPolicy: IfNotPresent
        name: ui-base
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "1"
        - name: TRACING_ENABLED
          value: "1"
        - name: KAFKA_ADDRESS
          value: ""
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadiumsvc
        - name: JAEGER_SERVICE_NAME
          value: ui.default
        - name: JAEGER_SAMPLER_TYPE
          value: ratelimiting
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system:14268/api/traces
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    project: mesh-arena
    app: ui
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
  selector:
    app: ui
---
