apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: ai
    version: locals
    vm: unknown
  name: ai-locals
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai
      version: locals
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        project: mesh-arena
        app: ai
        version: locals
        vm: unknown
    spec:
      containers:
      - image:
        imagePullPolicy: Never
        name: ai
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: KAFKA_ADDRESS
          value: ""
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadiumsvc
        - name: INTERACTIVE_MODE
          value: "0"
        - name: PLAYER_TEAM
          value: locals
        - name: PLAYER_ATTACKING
          value: "100"
        - name: PLAYER_COLOR
          value: "#0066CC"
        - name: USE_NAME_API
          value: "false"
        - name: PLAYER_NAMES
          value: Charbonneau,Arthur,Deniaud,Martin,Dufort,Séverin,Girard,Blanchet,Villeneuve,Tillery,Covington,George,Fraley,Hansen,Ramsey,Jennings,Hammond,Barnett,Mazzeo,Albano,Volta,Rosiello,Toscani,Frank,Sauer,Brandt,Krüger,Sedillo,Owen,Floyd,Comey,Gwilliam,Tew,Ordaz,Zambrano,Giron,Bailon
        - name: JAEGER_SERVICE_NAME
          value: ai.default
        - name: JAEGER_SAMPLER_TYPE
          value: ratelimiting
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system.svc/api/traces
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: ai
  labels:
    project: mesh-arena
    app: ai
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: ai
