apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: ball
    version: burst
  name: ball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ball
      version: burst
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        io.cilium.proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/8080/TCP/HTTP>"
      labels:
        project: mesh-arena
        app: ball
        version: burst
    spec:
      containers:
      - image:
        imagePullPolicy: Never
        name: ball
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: PCT_ERRORS
          value: "20"
        - name: RESISTANCE
          value: "120"
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: KAFKA_ADDRESS
          value: ""
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadiumsvc
        - name: CSS_TRANSITION
          value: "true"
        - name: DELTA_MS
          value: "200"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: ball
  labels:
    project: mesh-arena
    app: ball
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: ball
