apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: player
    version: locals
    vm: unknown
  name: player-locals
spec:
  replicas: 2
  selector:
    matchLabels:
      app: player
      version: locals
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        io.cilium.proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/8080/TCP/HTTP>"
      labels:
        project: mesh-arena
        app: player
        version: locals
        vm: unknown
    spec:
      containers:
      - image:
        imagePullPolicy: Never
        name: player
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: KAFKA_ADDRESS
          value: ""
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadiumsvc
        - name: INTERACTIVE_MODE
          value: "0"
        - name: PLAYER_TEAM
          value: locals
        - name: NO_TRANSITION
          value: "false"
        - name: DELTA_MS
          value: "300"
        - name: PLAYER_HUE
          value: "-120"
        - name: USE_NAME_API
          value: "false"
        - name: NAMES
          value: Charbonneau,Arthur,Deniaud,Martin,Dufort,Séverin,Girard,Blanchet,Villeneuve,Tillery,Covington,George,Fraley,Hansen,Ramsey,Jennings,Hammond,Barnett,Mazzeo,Albano,Volta,Rosiello,Toscani,Frank,Sauer,Brandt,Krüger,Sedillo,Owen,Floyd,Comey,Gwilliam,Tew,Ordaz,Zambrano,Giron,Bailon
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: player
  labels:
    project: mesh-arena
    app: player
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: player
