apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: player
    version: messi
    vm: unknown
  name: player-messi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player
      version: messi
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        io.cilium.proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/8080/TCP/HTTP>"
      labels:
        project: mesh-arena
        app: player
        version: messi
        vm: unknown
    spec:
      containers:
      - image:
        imagePullPolicy: Never
        name: player
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: KAFKA_ADDRESS
          value: ""
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadiumsvc
        - name: INTERACTIVE_MODE
          value: "0"
        - name: PLAYER_TEAM
          value: visitors
        - name: CSS_TRANSITION
          value: "true"
        - name: DELTA_MS
          value: "200"
        - name: USE_NAME_API
          value: "false"
        - name: NAMES
          value: Messi
        - name: PLAYER_SPEED
          value: "85"
        - name: PLAYER_ACCURACY
          value: "0.95"
        - name: PLAYER_SKILL
          value: "15"
        - name: PLAYER_SHOOT
          value: "300"
        - name: PLAYER_ATT_SHOOT_FAST
          value: "20"
        - name: PLAYER_HUE
          value: "25"
        - name: PLAYER_BRIGHTNESS
          value: "80"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
