apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    project: mesh-arena
  name: mesharena-global
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
status: {}