apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    project: mesh-arena
  name: mesharena-global
spec:
  ingress:
  - from:
    - podSelector: {}
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-ingress
  podSelector: {}
  policyTypes:
  - Ingress
status: {}
